# Generated by Django 4.0.4 on 2022-04-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=[('3', '3'), ('18', '18'), ('10', '10'), ('24', '24'), ('6', '6'), ('7', '7'), ('5', '5'), ('20', '20'), ('2', '2'), ('30', '30'), ('19', '19'), ('25', '25'), ('12', '12'), ('1', '1'), ('27', '27'), ('8', '8'), ('16', '16'), ('23', '23'), ('26', '26'), ('21', '21'), ('13', '13'), ('29', '29'), ('28', '28'), ('17', '17'), ('11', '11'), ('9', '9'), ('22', '22'), ('15', '15'), ('14', '14'), ('4', '4')], max_length=3)),
                ('time', models.CharField(choices=[('18', '18'), ('22', '22'), ('15', '15'), ('10', '10'), ('21', '21'), ('20', '20'), ('13', '13'), ('17', '17'), ('11', '11'), ('19', '19'), ('16', '16'), ('12', '12'), ('9', '9'), ('23', '23'), ('14', '14')], max_length=2)),
                ('month', models.CharField(choices=[('8', '8'), ('3', '3'), ('10', '10'), ('6', '6'), ('7', '7'), ('5', '5'), ('2', '2'), ('11', '11'), ('12', '12'), ('1', '1'), ('9', '9'), ('4', '4')], max_length=3)),
                ('tedad', models.CharField(choices=[('3', '3'), ('1', '1'), ('5', '5'), ('4', '4'), ('2', '2')], max_length=2)),
                ('fullname', models.CharField(max_length=250)),
                ('Note', models.TextField()),
            ],
        ),
    ]
